In [20]:
import numpy as np
import pandas as pd

In [21]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [22]:
file_path = "customer.csv" 

df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "dishantbhardwaj09/customer",
    file_path
)

print(df.head())

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [23]:
df = df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0: 2], df.iloc[:, -1], test_size=0.2)

In [25]:
from sklearn.preprocessing import OrdinalEncoder

In [26]:
X_train

     review education
22     Poor        PG
47     Good        PG
38     Good    School
5   Average    School
14     Poor        PG
31     Poor    School
0   Average    School
35     Poor    School
45     Poor        PG
41     Good        PG
37  Average        PG
23     Good    School
20  Average    School
16     Poor        UG
48     Good        UG
24  Average        PG
21  Average        PG
1      Poor        UG
13  Average    School
7      Poor    School
12     Poor    School
42     Good        PG
10     Good        UG
44  Average        UG
9      Good        UG
27     Poor        PG
43     Poor        PG
6      Good    School
46     Poor        PG
40     Good    School
3      Good        PG
30  Average        UG
49     Good        UG
15     Poor        UG
25     Good    School
2      Good        PG
28     Poor    School
34  Average    School
26     Poor        PG
4   Average        UG

In [27]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [28]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [29]:
OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [30]:
X_train = oe.transform(X_train)

In [31]:
X_train

array([[0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 1.],
       [1., 2.],
       [1., 2.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [1., 1.]])

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [33]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [34]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [35]:
y_train

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])